--------------------------------------------------------
-- BASELINE INICIAL - SECUENCIAS
--------------------------------------------------------

CREATE SEQUENCE SEQ_IV_AUDITORIA START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IV_CHAT_REGLA START WITH 21 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IV_CIRCULAR START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IV_DOCUMENTO_ADJUNTO START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IV_ENTIDAD_BASE START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IV_LOCALIDAD START WITH 7 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_IV_MUNICIPIO START WITH 9 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_IV_NOVEDAD START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IV_NOVEDAD_REQUISITO START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IV_REQUISITO START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IV_ROL START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IV_SECTOR START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IV_TIPO_INSTITUCION START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IV_TIPO_POBLACION START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IV_TRAMITE START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IV_TRAMITE_REQUISITO START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_IV_USUARIO START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_LOCALIDAD START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
