--------------------------------------------------------
-- BASELINE INICIAL - VISTAS
--------------------------------------------------------

CREATE OR REPLACE FORCE VIEW VISTA_REPORTE AS
SELECT
    e.ID_ENTIDAD,
    e.NOMBRE_EE AS NOMBRE_EE,
    NVL(s.NOMBRE, 'No Aplica') AS SEDE,
    NVL(ie.ESPECIALIDAD, 'No Aplica') AS ESPECIALIDAD,
    NVL(et.PROGRAMA, 'No Aplica') AS PROGRAMA,
    e.CODIGO_DANE AS DANE,
    t.NUMERO_RADICADO AS NUM_RADICADO,
    e.FECHA_CREACION AS FECHA,
    m.NOMBRE AS MUNICIPIO,
    NVL(tp.NOMBRE, 'No definido') AS TIPO_POBLACION,
    ti.NOMBRE AS TIPO_INSTITUCION,
    l.SECTOR,
    l.DIRECCION,
    NVL(t.ESTADO_TRAMITE, 'PENDIENTE') AS ESTADO,
    e.RESPONSABLE
FROM IV_ENTIDAD_BASE e
LEFT JOIN IV_TIPO_INSTITUCION ti
    ON e.ID_TIPO_INSTITUCION = ti.ID_TIPO_INSTITUCION
LEFT JOIN IV_TIPO_POBLACION tp
    ON e.ID_TIPO_POBLACION = tp.ID_TIPO_POBLACION
LEFT JOIN IV_LOCALIDAD l
    ON e.ID_ENTIDAD = l.ID_ENTIDAD
LEFT JOIN IV_MUNICIPIO m
    ON l.ID_MUNICIPIO = m.ID_MUNICIPIO
LEFT JOIN IV_TRAMITE t
    ON e.ID_ENTIDAD = t.ID_ENTIDAD
LEFT JOIN IV_IE ie
    ON e.ID_ENTIDAD = ie.ID_ENTIDAD
LEFT JOIN IV_ETDH et
    ON e.ID_ENTIDAD = et.ID_ENTIDAD
LEFT JOIN IV_SEDE s
    ON e.ID_ENTIDAD = s.ID_ENTIDAD;

CREATE OR REPLACE FORCE VIEW VISTA_TARJETAS AS
SELECT
    b_padre.CODIGO_DANE AS DANE_PRINCIPAL,
    b_padre.NOMBRE_EE AS NOMBRE_ENTIDAD_PADRE,
    'Institución Educativa' AS CATEGORIA_PADRE,
    s.NOMBRE AS NOMBRE_SEDE,
    b_hijo.CODIGO_DANE AS DANE_SEDE,
    NVL(l.SECTOR, 'No definido') AS SECTOR,
    m.NOMBRE AS MUNICIPIO,
    b_padre.CORREO,
    b_padre.TELEFONO,
    l.DIRECCION,
    b_padre.RESPONSABLE,
    NVL(p.NOMBRE, 'General') AS TIPO_POBLACION,
    NVL(
        (
            SELECT MAX(ESTADO_TRAMITE) KEEP (DENSE_RANK LAST ORDER BY FECHA_SOLICITUD, ID_TRAMITE)
            FROM IV_TRAMITE t
            WHERE t.ID_ENTIDAD = b_hijo.ID_ENTIDAD
               OR t.ID_ENTIDAD = b_padre.ID_ENTIDAD
        ),
        'PENDIENTE'
    ) AS ESTADO_SEGUIMIENTO
FROM IV_IE i
JOIN IV_ENTIDAD_BASE b_padre
    ON i.ID_ENTIDAD = b_padre.ID_ENTIDAD
LEFT JOIN IV_SEDE s
    ON i.ID_ENTIDAD = s.ID_IE_PADRE
LEFT JOIN IV_ENTIDAD_BASE b_hijo
    ON s.ID_ENTIDAD = b_hijo.ID_ENTIDAD
LEFT JOIN IV_LOCALIDAD l
    ON b_padre.ID_ENTIDAD = l.ID_ENTIDAD
LEFT JOIN IV_MUNICIPIO m
    ON l.ID_MUNICIPIO = m.ID_MUNICIPIO
LEFT JOIN IV_TIPO_POBLACION p
    ON b_padre.ID_TIPO_POBLACION = p.ID_TIPO_POBLACION

UNION ALL

SELECT
    b.CODIGO_DANE AS DANE_PRINCIPAL,
    b.NOMBRE_EE AS NOMBRE_ENTIDAD_PADRE,
    'ETDH' AS CATEGORIA_PADRE,
    NULL AS NOMBRE_SEDE,
    NULL AS DANE_SEDE,
    NVL(l.SECTOR, 'No definido') AS SECTOR,
    m.NOMBRE AS MUNICIPIO,
    b.CORREO,
    b.TELEFONO,
    l.DIRECCION,
    b.RESPONSABLE,
    NVL(p.NOMBRE, 'General') AS TIPO_POBLACION,
    NVL(
        (
            SELECT MAX(ESTADO_TRAMITE) KEEP (DENSE_RANK LAST ORDER BY FECHA_SOLICITUD, ID_TRAMITE)
            FROM IV_TRAMITE t
            WHERE t.ID_ENTIDAD = b.ID_ENTIDAD
        ),
        'PENDIENTE'
    ) AS ESTADO_SEGUIMIENTO
FROM IV_ETDH e
JOIN IV_ENTIDAD_BASE b
    ON e.ID_ENTIDAD = b.ID_ENTIDAD
LEFT JOIN IV_LOCALIDAD l
    ON b.ID_ENTIDAD = l.ID_ENTIDAD
LEFT JOIN IV_MUNICIPIO m
    ON l.ID_MUNICIPIO = m.ID_MUNICIPIO
LEFT JOIN IV_TIPO_POBLACION p
    ON b.ID_TIPO_POBLACION = p.ID_TIPO_POBLACION;

CREATE OR REPLACE FORCE VIEW VW_REQUISITOS_TRAMITE AS
SELECT
    r.ID_REQUISITO,
    tr.ID_TRAMITE,
    r.NOMBRE AS REQUISITO_DOCUMENTAL,
    NVL(d.RUTA_ARCHIVO, 'Sin archivo') AS CARGAR_PDF,
    NVL(t.ESTADO_TRAMITE, 'Pendiente') AS ESTADO,
    NVL(u.NOMBRE || ' ' || u.APELLIDO, 'Sin responsable') AS RESPONSABLE,
    NVL(tr.OBSERVACION, 'Sin observación') AS OBSERVACION_REQUISITO
FROM IV_REQUISITO r
LEFT JOIN IV_TRAMITE_REQUISITO tr
    ON r.ID_REQUISITO = tr.ID_REQUISITO
LEFT JOIN IV_TRAMITE t
    ON tr.ID_TRAMITE = t.ID_TRAMITE
LEFT JOIN IV_DOCUMENTO_ADJUNTO d
    ON tr.ID_TRAMITE_REQUISITO = d.ID_TRAMITE_REQUISITO
LEFT JOIN IV_USUARIO u
    ON t.ID_USUARIO_RESPONSABLE = u.ID_USUARIO
WHERE r.ACTIVO = 'S';
