--------------------------------------------------------
-- BASELINE INICIAL - TABLAS
--------------------------------------------------------

CREATE TABLE IV_ROL (
    ID_ROL NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(200),
    ACTIVO CHAR(1) DEFAULT 'S',
    CONSTRAINT CK_IV_ROL_ACTIVO CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE IV_USUARIO (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50),
    CORREO VARCHAR2(100) NOT NULL,
    CONTRASENA VARCHAR2(256) NOT NULL,
    ID_ROL NUMBER NOT NULL,
    ESTADO VARCHAR2(15) DEFAULT 'ACTIVO',
    FECHA_CREACION DATE DEFAULT SYSDATE,
    CONSTRAINT UQ_IV_USUARIO_CORREO UNIQUE (CORREO),
    CONSTRAINT FK_USU_ROL FOREIGN KEY (ID_ROL)
        REFERENCES IV_ROL (ID_ROL)
);

CREATE TABLE IV_TIPO_INSTITUCION (
    ID_TIPO_INSTITUCION NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE IV_TIPO_POBLACION (
    ID_TIPO_POBLACION NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE IV_DEPARTAMENTO (
    ID_DEPARTAMENTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE IV_REQUISITO (
    ID_REQUISITO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(300) NOT NULL,
    ACTIVO CHAR(1) DEFAULT 'S',
    CONSTRAINT UQ_REQUISITO_NOMBRE UNIQUE (NOMBRE),
    CONSTRAINT CK_IV_REQUISITO_ACTIVO CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE IV_CIRCULAR (
    ID_CIRCULAR NUMBER PRIMARY KEY,
    NUM_TITULO VARCHAR2(150) NOT NULL,
    DESCRIPCION VARCHAR2(200) NOT NULL,
    FECHA_EMISION DATE NOT NULL,
    VIGENTE CHAR(1) DEFAULT 'S',
    ID_USUARIO_REGISTRA NUMBER NOT NULL,
    CONSTRAINT CK_IV_CIRCULAR_VIGENTE CHECK (VIGENTE IN ('S','N')),
    CONSTRAINT FK_CIRC_USU FOREIGN KEY (ID_USUARIO_REGISTRA)
        REFERENCES IV_USUARIO (ID_USUARIO)
);

CREATE TABLE IV_ENTIDAD_BASE (
    ID_ENTIDAD NUMBER PRIMARY KEY,
    ID_TIPO_INSTITUCION NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    NOMBRE_EE VARCHAR2(200) NOT NULL,
    NIT VARCHAR2(100) NOT NULL,
    CODIGO_DANE VARCHAR2(100) NOT NULL,
    CORREO VARCHAR2(100) NOT NULL,
    TELEFONO VARCHAR2(30) NOT NULL,
    ID_TIPO_POBLACION NUMBER NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    RESPONSABLE VARCHAR2(100) NOT NULL,
    CONSTRAINT UQ_ENTIDAD_DANE UNIQUE (CODIGO_DANE),
    CONSTRAINT UQ_ENTIDAD_NIT UNIQUE (NIT),
    CONSTRAINT FK_BASE_TIPO_INS FOREIGN KEY (ID_TIPO_INSTITUCION)
        REFERENCES IV_TIPO_INSTITUCION (ID_TIPO_INSTITUCION),
    CONSTRAINT FK_BASE_POB FOREIGN KEY (ID_TIPO_POBLACION)
        REFERENCES IV_TIPO_POBLACION (ID_TIPO_POBLACION),
    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES IV_USUARIO (ID_USUARIO)
);

CREATE TABLE IV_IE (
    ID_ENTIDAD NUMBER PRIMARY KEY,
    ESPECIALIDAD VARCHAR2(150),
    RESOLUCION_APROBACION VARCHAR2(150),
    CONSTRAINT FK_IE_BASE FOREIGN KEY (ID_ENTIDAD)
        REFERENCES IV_ENTIDAD_BASE (ID_ENTIDAD)
);

CREATE TABLE IV_ETDH (
    ID_ENTIDAD NUMBER PRIMARY KEY,
    RESOLUCION VARCHAR2(150) NOT NULL,
    PROGRAMA VARCHAR2(150) NOT NULL,
    NIVEL_FORMACION VARCHAR2(150) NOT NULL,
    MODALIDAD_ETDH VARCHAR2(150) NOT NULL,
    RESOLUCION_APROBACION VARCHAR2(150) NOT NULL,
    DURACION_MESES NUMBER NOT NULL,
    CONSTRAINT FK_ETDH_BASE FOREIGN KEY (ID_ENTIDAD)
        REFERENCES IV_ENTIDAD_BASE (ID_ENTIDAD)
);

CREATE TABLE IV_MUNICIPIO (
    ID_MUNICIPIO NUMBER PRIMARY KEY,
    CODIGO_DANE NUMBER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    ID_DEPARTAMENTO NUMBER NOT NULL,
    CONSTRAINT UQ_IV_MUNICIPIO_DANE UNIQUE (CODIGO_DANE),
    CONSTRAINT FK_MUN_DEP FOREIGN KEY (ID_DEPARTAMENTO)
        REFERENCES IV_DEPARTAMENTO (ID_DEPARTAMENTO)
);

CREATE TABLE IV_LOCALIDAD (
    ID_LOCALIDAD NUMBER PRIMARY KEY,
    ID_ENTIDAD NUMBER NOT NULL,
    DIRECCION VARCHAR2(100) NOT NULL,
    ID_MUNICIPIO NUMBER NOT NULL,
    SECTOR VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_EDENTI FOREIGN KEY (ID_ENTIDAD)
        REFERENCES IV_ENTIDAD_BASE (ID_ENTIDAD),
    CONSTRAINT FK_LOC_MUN FOREIGN KEY (ID_MUNICIPIO)
        REFERENCES IV_MUNICIPIO (ID_MUNICIPIO)
);

CREATE TABLE IV_SEDE (
    ID_ENTIDAD NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    ID_IE_PADRE NUMBER,
    CONSTRAINT FK_SEDE_BASE FOREIGN KEY (ID_ENTIDAD)
        REFERENCES IV_ENTIDAD_BASE (ID_ENTIDAD),
    CONSTRAINT FK_SEDE_IE FOREIGN KEY (ID_IE_PADRE)
        REFERENCES IV_IE (ID_ENTIDAD)
);

CREATE TABLE IV_NOVEDAD (
    ID_NOVEDAD NUMBER PRIMARY KEY,
    ID_CIRCULAR NUMBER NOT NULL,
    TIPO_NOVEDAD VARCHAR2(200) NOT NULL,
    ACTIVO CHAR(1) DEFAULT 'S',
    ID_NOVEDAD_PADRE NUMBER,
    CONSTRAINT CK_IV_NOVEDAD_ACTIVO CHECK (ACTIVO IN ('S','N')),
    CONSTRAINT FK_NOV_CIRC FOREIGN KEY (ID_CIRCULAR)
        REFERENCES IV_CIRCULAR (ID_CIRCULAR),
    CONSTRAINT FK_NOV_PADRE FOREIGN KEY (ID_NOVEDAD_PADRE)
        REFERENCES IV_NOVEDAD (ID_NOVEDAD)
);

CREATE TABLE IV_NOVEDAD_REQUISITO (
    ID_NOVEDAD_REQUISITO NUMBER PRIMARY KEY,
    ID_NOVEDAD NUMBER NOT NULL,
    ID_REQUISITO NUMBER NOT NULL,
    CONSTRAINT UQ_N_R_V4 UNIQUE (ID_NOVEDAD, ID_REQUISITO),
    CONSTRAINT FK_NR_NOV FOREIGN KEY (ID_NOVEDAD)
        REFERENCES IV_NOVEDAD (ID_NOVEDAD),
    CONSTRAINT FK_NR_REQ FOREIGN KEY (ID_REQUISITO)
        REFERENCES IV_REQUISITO (ID_REQUISITO)
);

CREATE TABLE IV_TRAMITE (
    ID_TRAMITE NUMBER PRIMARY KEY,
    NUMERO_RADICADO VARCHAR2(50) NOT NULL,
    ID_ENTIDAD NUMBER NOT NULL,
    ID_NOVEDAD NUMBER NOT NULL,
    ESTADO_TRAMITE VARCHAR2(50),
    FECHA_SOLICITUD DATE DEFAULT SYSDATE,
    ID_USUARIO_RESPONSABLE NUMBER NOT NULL,

    CONSTRAINT UQ_IV_TRAMITE_RADICADO UNIQUE (NUMERO_RADICADO),

    CONSTRAINT CK_IV_TRAMITE_ESTADO CHECK (
        ESTADO_TRAMITE IN (
            'RADICADO',
            'EN DESARROLLO',
            'AVANZADO',
            'TERMINADO'
        )
    ),

    CONSTRAINT FK_TR_NOV FOREIGN KEY (ID_NOVEDAD)
        REFERENCES IV_NOVEDAD (ID_NOVEDAD),

    CONSTRAINT FK_TR_USU FOREIGN KEY (ID_USUARIO_RESPONSABLE)
        REFERENCES IV_USUARIO (ID_USUARIO)
);

CREATE TABLE IV_TRAMITE_REQUISITO (
    ID_TRAMITE_REQUISITO NUMBER PRIMARY KEY,
    ID_TRAMITE NUMBER NOT NULL,
    ID_REQUISITO NUMBER NOT NULL,
    ESTADO_REVISION VARCHAR2(50) DEFAULT 'PENDIENTE',
    OBSERVACION VARCHAR2(200),
    CONSTRAINT UQ_TR_REQ UNIQUE (ID_TRAMITE, ID_REQUISITO),
    CONSTRAINT FK_TRR_TR FOREIGN KEY (ID_TRAMITE)
        REFERENCES IV_TRAMITE (ID_TRAMITE),
    CONSTRAINT FK_TRR_REQ FOREIGN KEY (ID_REQUISITO)
        REFERENCES IV_REQUISITO (ID_REQUISITO)
);

CREATE TABLE IV_DOCUMENTO_ADJUNTO (
    ID_DOCUMENTO NUMBER PRIMARY KEY,
    ID_TRAMITE_REQUISITO NUMBER NOT NULL,
    NOMBRE_ARCHIVO VARCHAR2(200) NOT NULL,
    RUTA_ARCHIVO VARCHAR2(500) NOT NULL,
    ID_USUARIO_CARGA NUMBER NOT NULL,
    FECHA_CARGA DATE DEFAULT SYSDATE,
    CONSTRAINT FK_DOC_TRR FOREIGN KEY (ID_TRAMITE_REQUISITO)
        REFERENCES IV_TRAMITE_REQUISITO (ID_TRAMITE_REQUISITO)
        ON DELETE CASCADE,
    CONSTRAINT FK_DOC_USU FOREIGN KEY (ID_USUARIO_CARGA)
        REFERENCES IV_USUARIO (ID_USUARIO)
);

CREATE TABLE IV_CHAT_REGLA (
    ID_REGLA NUMBER PRIMARY KEY,
    PATRON VARCHAR2(200) NOT NULL,
    SINONIMOS VARCHAR2(500),
    TIPO_ACCION VARCHAR2(50) NOT NULL,
    NOMBRE_TABLA VARCHAR2(50),
    COLUMNA_ESTADO VARCHAR2(50),
    COLUMNA_PARAMETRO VARCHAR2(50),
    RESPUESTA VARCHAR2(500),
    ACTIVO CHAR(1) DEFAULT 'S',
    FECHA_CREACION DATE DEFAULT SYSDATE,
    USUARIO_CREACION VARCHAR2(50) DEFAULT USER,
    CONSTRAINT CK_IV_CHAT_REGLA_ACTIVO CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE IV_AUDITORIA (
    ID_AUDITORIA NUMBER PRIMARY KEY,
    TABLA_AFECTADA VARCHAR2(50) NOT NULL,
    OPERACION VARCHAR2(10) NOT NULL,
    USUARIO VARCHAR2(50) NOT NULL,
    FECHA DATE DEFAULT SYSDATE,
    VALOR_ANTERIOR CLOB,
    VALOR_NUEVO CLOB
);
